/**
 * Autogenerated by Thrift Compiler (0.9.3)
 *
 * DO NOT EDIT UNLESS YOU ARE SURE THAT YOU KNOW WHAT YOU ARE DOING
 *  @generated
 */
#ifndef CTAAtsMsg_CONSTANTS_H
#define CTAAtsMsg_CONSTANTS_H

#include "CTAAtsMsg_types.h"

namespace CTAMsg {

class CTAAtsMsgConstants {
 public:
  CTAAtsMsgConstants();

};

extern const CTAAtsMsgConstants g_CTAAtsMsg_constants;

} // namespace

#endif
