/**
 * Autogenerated by Thrift Compiler (0.9.3)
 *
 * DO NOT EDIT UNLESS YOU ARE SURE THAT YOU KNOW WHAT YOU ARE DOING
 *  @generated
 */
#include "CTAAtsMsg_constants.h"

namespace CTAMsg {

const CTAAtsMsgConstants g_CTAAtsMsg_constants;

CTAAtsMsgConstants::CTAAtsMsgConstants() {
}

} // namespace

